# This is a basic workflow to help you get started with Actions

name: CI-build-macos

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - "**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-10.15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: setup project
        run: | 
          npm install
        
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Install Qt
        # You may pin to the exact commit or the version.
        uses: jurplel/install-qt-action@v2
        with:
          # Directory to install Qt - When possible, access your Qt directory through the Qt5_DIR or Qt6_DIR environment variable
          # dir: # optional
          
          # Version of Qt to install
          version: 6.2.2
          
          # Host platform
          host: mac
          
          # Target platform for build
          target: desktop
          
          # Architecture for Windows/Android
          #arch: # optional
          
          # Whether or not to install Qt dependencies on Linux
          #install-deps: # optional, default is true
          
          # Additional Qt modules to install
          #modules: # optional
          
          # Whether or not to actually download Qt
          #cached: # optional, default is false
          
          # Whether or not to automatically run setup-python to find a valid python version.
          #setup-python: # optional, default is true
          
          # Qt tools to download--specify comma-separated argument lists which are themselves separated by spaces: <tool_name>,<tool_version>,<tool_arch>
          #tools: # optional
          
          # Whether or not to set environment variables after running aqtinstall
          #set-env: # optional, default is true
          
          # Whether or not to actually install Qt or just the tools from the tools argument
          #tools-only: # optional, default is false
          
          # Version of aqtinstall to use in case of issues
          #aqtversion: # optional, default is ==1.2.5
          
          # Version of py7zr to use in case of issues
          #py7zrversion: # optional, default is ==0.16.1
          
          # Any extra arguments to append to the back
          
      # Runs a single command using the runners shell
      - name: Signal the end       
        run: echo Well Done 
